name: 'Build Container Image'
on:
  push:
    branches: main
  workflow_dispatch:
env:
  DOCKERHUB_ID: ${{ secrets.DOCKERHUB_ID }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  build-container-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout to the repository on the build machine
      - name: Checkout
        uses: actions/checkout@v3
      # checkout to the repository on the build machine
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Build Node
        run: npm install && npm build
      # login to Docker Hub using the secrets provided
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # create a buildkit builder instance
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      # build the container image and push it to DockerHub.
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_ID }}/demo-app:dev